image_root: 'PAB/'
test_file: 'PAB/annotation/test/attr.json'
# OOD test set
#test_file: 'PAB/annotation/test/ucc.json'


train_file:  [
  'PAB/annotation/train/attr_0.json', 'PAB/annotation/train/attr_1.json',
  'PAB/annotation/train/attr_2.json', 'PAB/annotation/train/attr_3.json',
  'PAB/annotation/train/attr_4.json', 'PAB/annotation/train/attr_5.json',
  'PAB/annotation/train/attr_6.json', 'PAB/annotation/train/attr_7.json',
  'PAB/annotation/train/attr_8.json', 'PAB/annotation/train/attr_9.json',

  'PAB/annotation/train/attr_10.json', 'PAB/annotation/train/attr_11.json',
  'PAB/annotation/train/attr_12.json', 'PAB/annotation/train/attr_13.json',
  'PAB/annotation/train/attr_14.json', 'PAB/annotation/train/attr_15.json',
  'PAB/annotation/train/attr_16.json', 'PAB/annotation/train/attr_17.json',
  'PAB/annotation/train/attr_18.json', 'PAB/annotation/train/attr_19.json',

  'PAB/annotation/train/attr_20.json', 'PAB/annotation/train/attr_21.json',
  'PAB/annotation/train/attr_22.json', 'PAB/annotation/train/attr_23.json',
  'PAB/annotation/train/attr_24.json', 'PAB/annotation/train/attr_25.json',
  'PAB/annotation/train/attr_26.json', 'PAB/annotation/train/attr_27.json',
  'PAB/annotation/train/attr_28.json', 'PAB/annotation/train/attr_29.json',

  'PAB/annotation/train/attr_30.json', 'PAB/annotation/train/attr_31.json',
  'PAB/annotation/train/attr_32.json', 'PAB/annotation/train/attr_33.json',
  'PAB/annotation/train/attr_34.json', 'PAB/annotation/train/attr_35.json',
  'PAB/annotation/train/attr_36.json', 'PAB/annotation/train/attr_37.json',
  'PAB/annotation/train/attr_38.json', 'PAB/annotation/train/attr_39.json',

  'PAB/annotation/train/attr_40.json', 'PAB/annotation/train/attr_41.json',
  'PAB/annotation/train/attr_42.json', 'PAB/annotation/train/attr_43.json',
  'PAB/annotation/train/attr_44.json', 'PAB/annotation/train/attr_45.json',
  'PAB/annotation/train/attr_46.json', 'PAB/annotation/train/attr_47.json',
  'PAB/annotation/train/attr_48.json', 'PAB/annotation/train/attr_49.json',

  'PAB/annotation/train/attr_50.json', 'PAB/annotation/train/attr_51.json',
  'PAB/annotation/train/attr_52.json', 'PAB/annotation/train/attr_53.json',
  'PAB/annotation/train/attr_54.json', 'PAB/annotation/train/attr_55.json',
  'PAB/annotation/train/attr_56.json', 'PAB/annotation/train/attr_57.json',
  'PAB/annotation/train/attr_58.json', 'PAB/annotation/train/attr_59.json',

  'PAB/annotation/train/attr_60.json', 'PAB/annotation/train/attr_61.json',
  'PAB/annotation/train/attr_62.json', 'PAB/annotation/train/attr_63.json',
  'PAB/annotation/train/attr_64.json', 'PAB/annotation/train/attr_65.json',
  'PAB/annotation/train/attr_66.json', 'PAB/annotation/train/attr_67.json',
  'PAB/annotation/train/attr_68.json', 'PAB/annotation/train/attr_69.json',

  'PAB/annotation/train/attr_70.json', 'PAB/annotation/train/attr_71.json',
  'PAB/annotation/train/attr_72.json', 'PAB/annotation/train/attr_73.json',
  'PAB/annotation/train/attr_74.json',
]


## Image Encoder
vision_config: 'configs/config_beit2_base.json'
h: 224
w: 224

## Text Encoder
text_config: 'configs/config_bert.json'
text_encoder: 'bert-base-uncased'
text_num_hidden_layers: 18
text_fusion_start_at: 12

use_beit_v2: True
image_res: 224
patch_size: 16
sdm:
  use_sdm: False

id:
  use_id: False

## Training
load_params: False
load_pretrained: True

max_words: 77
max_tokens: 77
eda_p: 1
erasing_p: 0.6

batch_size_train: 22
batch_size_test: 32
batch_size_test_text: 150

embed_dim: 256 #2048
num_actions: 875
itc_dp: 0.5
temp: 0.07
label_smooth: 0.2

## mlm loss

mlm:
  is_mlm: True

mask_prob: 0.4
max_masks: 12
skipgram_prb: 0.2
skipgram_size: 3
mask_whole_word: True

itm:
  weight: 4.0
  use_mask: True

mim:
  weight: 4.0
  use_mim: True
  mask_ratio: 0.5

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: step, lr: 2e-5, epochs: 20, num_warmup_steps: 500}

k_test: 128


icfg_rstp: False

be_hard: True
be_pose_img: False
pose_conv: False

eda: True

top_k: 3
entropy_tau: 1.0

# Method-aligned defaults.
# Set action_mapper_input to 'projected' to estimate Phi_act(v) from the shared visual feature v_proj.
# Set cls_target to 'query' to align Lcls with the full query text feature instead of the action codebook anchor.
action_mapper_input: 'projected'
cls_target: 'query'


action_list: [
    "accepting",
    "accident",
    "acrobatics",
    "acting",
    "action",
    "aerobics",
    "affection",
    "aiming",
    "air horn",
    "alcohol",
    "annoyed",
    "applying makeup",
    "approaching",
    "archery",
    "arm wrestling",
    "armwrestling",
    "army training exercise",
    "asking",
    "assembling",
    "assisting",
    "attacking",
    "avoiding",
    "awakening",
    "axing",
    "baby",
    "baby reveal",
    "backfiring",
    "backflipping",
    "backing",
    "badminton",
    "bail",
    "baking",
    "balancing",
    "ballet",
    "baptism",
    "baptizing",
    "bar",
    "barbering",
    "bartending",
    "baseball",
    "basket-making",
    "basketball",
    "bathing",
    "batter",
    "batting",
    "beach",
    "bed spring breaks",
    "beehive",
    "beer",
    "beer pong",
    "belly flop",
    "bench",
    "bench pressing",
    "bending",
    "bicycling",
    "biking",
    "birthday",
    "biting",
    "bitting",
    "blacksmithing",
    "blaming",
    "blending",
    "blindfold",
    "blocking",
    "blowing",
    "bmx biking",
    "bmx racing",
    "boarding",
    "boating",
    "body slamming",
    "bodyboarding",
    "bodybuilding",
    "bonding",
    "boogie boarding",
    "bookshelf",
    "booping",
    "bouncing",
    "bowling",
    "box jumping",
    "boxing",
    "boy",
    "brakedancing",
    "breaking",
    "bride",
    "bringing",
    "brushing",
    "brushing hair",
    "bucking",
    "building",
    "bumping",
    "burning",
    "bursting",
    "busted her ass",
    "butthole",
    "cable break",
    "cake",
    "calisthenics",
    "calling",
    "camera",
    "candle",
    "canoeing",
    "car",
    "care",
    "caressing",
    "carressing",
    "carring child",
    "carrying",
    "cartwheeling",
    "catcher",
    "catching",
    "celebrating",
    "cementing",
    "ceremony",
    "chainsawing",
    "chair",
    "champagne",
    "charging",
    "chasing",
    "checking car",
    "cheering",
    "cheerleading",
    "cheese",
    "chemistry",
    "chest",
    "child",
    "chin-up",
    "choking",
    "chopping",
    "choreographing",
    "christmas",
    "chugging",
    "cinnamon challenge",
    "circling",
    "clapping",
    "clawing",
    "cleaning",
    "climbing",
    "clinking glasses",
    "closed",
    "closing drawer",
    "clotheslined",
    "clowning",
    "collapsing",
    "colliding",
    "communication",
    "competing",
    "confetti",
    "consoling",
    "constructing",
    "controlling",
    "conversing",
    "cooking",
    "cooling down",
    "coordination",
    "costume removal",
    "costuming",
    "coughing",
    "counting",
    "covering",
    "cracking",
    "crashing",
    "crawling",
    "creating",
    "crossing",
    "crotch",
    "crouching",
    "crowded",
    "crushed hands",
    "crying",
    "cup",
    "cupcake",
    "curling",
    "curse",
    "cussing",
    "cutting",
    "damaging",
    "dancing",
    "daughter",
    "dead lifting",
    "deadlifting",
    "deafness",
    "decorating",
    "defeated",
    "defending",
    "delivering drinks",
    "demonstrating",
    "dentistry",
    "dentures",
    "descending",
    "destroying",
    "detaching",
    "digging",
    "dinosaur",
    "dirt biking",
    "disappointed",
    "disappointment",
    "distracting",
    "distraction",
    "diving",
    "dizzy",
    "docking",
    "docking boat",
    "dodgeball",
    "dodging",
    "dog",
    "doing push-ups",
    "dragging",
    "drenched",
    "dressing",
    "dribbling",
    "drilling",
    "drinking",
    "dropping",
    "drumming",
    "drunk",
    "ducking",
    "dueling",
    "dumbbell exercises",
    "dumping",
    "dunking",
    "eating",
    "education",
    "egg tossing",
    "electric shock",
    "electrical repair",
    "electrocuted",
    "electrocution",
    "elephant",
    "elliptical",
    "elliptical training",
    "embarrassed",
    "embracing",
    "engagement ring",
    "entering",
    "entertainment",
    "escalator",
    "escaping",
    "evading",
    "examining",
    "excited",
    "excitement",
    "exercising",
    "exiting",
    "experimenting",
    "explaining",
    "exploding",
    "exploring",
    "exposing",
    "extending rubber tube",
    "eye injury",
    "face-plants",
    "faceplanting",
    "failing",
    "fainting",
    "falling",
    "family",
    "farmer's walk",
    "farting",
    "fashion show",
    "father",
    "fear",
    "feeding",
    "feeding animals",
    "fencing",
    "fighting",
    "filling",
    "filming",
    "finding",
    "firefighting",
    "fireworks",
    "firing",
    "fishing",
    "fitting",
    "fixing light fixture",
    "flag standing",
    "flailing",
    "flaming",
    "flattening",
    "fleeing",
    "flicking",
    "flinches",
    "flinging",
    "flipping",
    "flipping mug",
    "floating",
    "floored",
    "flying",
    "foaming",
    "folding table",
    "following",
    "football",
    "freaked out",
    "free-kicking",
    "frightened",
    "frisbee",
    "frowning",
    "frustrated",
    "frustration",
    "fumbling",
    "garter tossing",
    "gathering",
    "gender reveal",
    "gesturing",
    "getting wet",
    "girl",
    "giving",
    "glass breaks",
    "gliding",
    "go-karting",
    "goalie",
    "goalkeeping",
    "golfing",
    "goofing off",
    "grabbing",
    "graduating",
    "grasping",
    "grass",
    "greeting",
    "grilling",
    "grinding",
    "grinning",
    "grocery shopping",
    "groin",
    "group dancing",
    "gun malfunction",
    "gym",
    "gymnastics",
    "hair",
    "hair entanglement",
    "hair wrapped",
    "haircutting",
    "hammering",
    "handstanding",
    "hanging",
    "happiness",
    "hat came off",
    "head bang",
    "head butted",
    "head-banging",
    "headbanging",
    "headbutting",
    "heading",
    "helmet-flipping",
    "helping",
    "hiding",
    "high five",
    "high-fiving",
    "hiking",
    "hitting",
    "hockey",
    "holding",
    "hooked",
    "hooping",
    "hooverboarding",
    "hopping",
    "hose handling",
    "hosing",
    "hoverboarding",
    "hugging",
    "hula-hooping",
    "hulahoop breaks",
    "hulahooping",
    "human pyramid",
    "humping",
    "hurdling",
    "hurting",
    "ice",
    "ignited",
    "in the image",
    "inflating balloon",
    "injection",
    "injuring",
    "injury",
    "inspecting car",
    "installing light fixture",
    "insulting",
    "inter tubing",
    "interacting",
    "interrupting",
    "interviewing",
    "introducing animals",
    "jeans",
    "jet-skiing",
    "joining the fight",
    "jousting",
    "joy",
    "juggling",
    "juicing",
    "jumping",
    "jumprope",
    "karate",
    "kayaking",
    "keg",
    "kickback",
    "kickboxing",
    "kicking",
    "killing fly",
    "kissing",
    "kitchen",
    "kneading face",
    "kneed",
    "kneeing",
    "kneeling",
    "knocking",
    "lacrosse",
    "ladder",
    "landing",
    "language",
    "laughing",
    "launching",
    "laundry",
    "laying",
    "leading",
    "leaking",
    "leaning",
    "leapfrogging",
    "learning",
    "leaving",
    "leg lifting",
    "leveling",
    "licked",
    "lifting",
    "lighting",
    "limbo",
    "listening to music",
    "loading",
    "locking",
    "looking",
    "loose",
    "loosening",
    "lost",
    "love",
    "lunging",
    "lying",
    "machine breaks",
    "magic",
    "mail delivery",
    "making",
    "malfunction",
    "man",
    "marriage",
    "martial arts training",
    "masking",
    "meditating",
    "messy",
    "misfire",
    "misjudged",
    "misplacing",
    "mispronunciation",
    "missing",
    "misunderstanding",
    "mixing",
    "modeling",
    "monkey",
    "monster",
    "moonwalking",
    "mopping",
    "moshing",
    "motorcycling",
    "mountain biking",
    "mounting",
    "movement",
    "moving",
    "mowing",
    "multi-tasking",
    "muscle-up",
    "napping",
    "nosebleed",
    "noticing",
    "nunchuck",
    "nunchuck demonstration",
    "nuzzling",
    "observing",
    "obstacle course",
    "opening",
    "opening box",
    "operating",
    "ordering",
    "outdoor activity",
    "outrun",
    "overboard",
    "overcrowding",
    "overestimated",
    "overfilling",
    "overflowing",
    "overloading",
    "overshot",
    "overwhelmed",
    "own goal",
    "paddleboarding",
    "paddling",
    "painting",
    "panicking",
    "paper",
    "parachuting",
    "parading",
    "parenting",
    "park",
    "parking enforcement",
    "parkour",
    "partying",
    "passing",
    "peace sign",
    "pedestrian crossing",
    "peed",
    "peeing",
    "peeking",
    "peeling",
    "performing",
    "petting",
    "phone",
    "photographing",
    "physical",
    "picking",
    "pig",
    "piggybacking",
    "piling up",
    "pillow fight",
    "pinata",
    "pink",
    "pinning",
    "pit crew",
    "pitcher",
    "pitching",
    "placing",
    "planking",
    "planting",
    "planting pole",
    "platforming",
    "playful",
    "playing",
    "pogo-sticking",
    "pogoing",
    "pointing",
    "poking",
    "pole dancing",
    "police",
    "polling",
    "pool",
    "poolside",
    "pooping",
    "poops his pants",
    "popped",
    "popping",
    "posing",
    "potatoe sack race",
    "pouring",
    "powerlifting",
    "practicing kicking",
    "pranking",
    "premature",
    "preparing",
    "presenting",
    "pretending",
    "pride",
    "prom",
    "promposal",
    "pronouncing",
    "proposing",
    "pubic",
    "puking",
    "pulling",
    "pumping gas",
    "pumpkin",
    "pumpkin carving",
    "punching",
    "pushing",
    "pushup",
    "putting",
    "puzzling",
    "racing",
    "rafting",
    "raking",
    "ramming",
    "ramp",
    "reaching",
    "reading",
    "receiving",
    "reclining",
    "recoil",
    "recording",
    "refereeing",
    "reflection",
    "refueling",
    "refused to jump",
    "rejected",
    "relaxing",
    "release",
    "remodeling",
    "removing clothing",
    "reporting",
    "resting",
    "riding",
    "ripping",
    "roaring",
    "robbery",
    "rocket",
    "rollerblading",
    "rollerskating",
    "rolling",
    "rolling stroller",
    "roofing",
    "room",
    "rope exercises",
    "rotating",
    "rough housing",
    "rounding up",
    "rowing",
    "rubber tube",
    "rubbing",
    "ruined",
    "running",
    "sabering",
    "sack racing",
    "sailing",
    "sake bombs",
    "sand in face",
    "sandboarding",
    "sawing",
    "scaring",
    "science experiment",
    "scooter",
    "scratching",
    "screaming",
    "sealing",
    "searching",
    "seasawing",
    "seesawing",
    "self-harm",
    "self-inflicted injury",
    "selfie-taking",
    "serving",
    "setting up",
    "shaking",
    "sharing",
    "shattering",
    "shaving",
    "sheathing blade",
    "sheep herding",
    "shifting",
    "shocking",
    "shooting",
    "shoplifting",
    "shopping",
    "shorted it out",
    "shotgunning",
    "shouting",
    "shoveling",
    "shoving",
    "showering",
    "showing",
    "shredded",
    "shutting door",
    "sing",
    "sinking",
    "sitting",
    "skateboarder",
    "skateboarding",
    "skating",
    "skidded down",
    "skiing",
    "skimboarding",
    "slamming",
    "slamming guitar",
    "slamming tablet",
    "slapping",
    "sled",
    "sledding",
    "sleeping",
    "slicing snowman",
    "sliding",
    "slings back",
    "slingshotting",
    "slippery",
    "slipping",
    "slips",
    "slumping",
    "smacking",
    "smacking chin",
    "smashing",
    "smeared",
    "smiling",
    "smoking",
    "snagging",
    "snapchat",
    "snapping",
    "snatched",
    "sneaking",
    "sneezing",
    "sniffing",
    "snowboarding",
    "snowmobiling",
    "snuggling",
    "soaked",
    "soccer",
    "socializing",
    "softball",
    "solving puzzle",
    "somersaulting",
    "somerseaulting",
    "sparring",
    "spazzing out",
    "speaking",
    "spearfishing",
    "spearing",
    "spectating",
    "speech",
    "speeding",
    "spider prank",
    "spiking",
    "spilling",
    "spinning",
    "spitting",
    "splashing",
    "splattered",
    "splits",
    "spotting",
    "spraying",
    "sprinkler",
    "squash",
    "squatting",
    "squeezing",
    "squirt",
    "stabbing",
    "stacking",
    "staggering",
    "stake",
    "standing",
    "staring",
    "starting bike",
    "startled",
    "startling",
    "statue lifting",
    "stealing",
    "steering",
    "stocking shelves",
    "straddling",
    "straightening hair",
    "streaking",
    "stretching",
    "strip dancing",
    "striping",
    "stripper",
    "struck",
    "struggling",
    "studying",
    "stumbling",
    "stunt",
    "summersalt",
    "sunbathing",
    "support",
    "surfing",
    "surprise",
    "surprised",
    "surprising",
    "swallowing",
    "swatting",
    "swearing",
    "sweeping",
    "swimming",
    "swing",
    "swiping",
    "sword",
    "swording",
    "synchronized dancing",
    "tablet grab",
    "tablet theft",
    "tackling",
    "taking",
    "talking",
    "tangled",
    "tantrum",
    "taping",
    "tapping railing",
    "target practice",
    "tattooing",
    "teaching",
    "tearing",
    "teasing",
    "teeing off",
    "teeter totter",
    "telling",
    "tennis",
    "testicles",
    "testing fence",
    "throwing",
    "ticketing",
    "tipped",
    "toasting",
    "togetherness",
    "toilet training",
    "tooth loss",
    "topple",
    "torn",
    "tossing",
    "tossing controllers",
    "touching",
    "towing",
    "training",
    "trampoline",
    "transporting drinks",
    "trapped",
    "trash can",
    "treadmill",
    "tree",
    "trick",
    "trimming",
    "tripping",
    "trust fall",
    "trustfall",
    "try",
    "tug-of-war",
    "tumbling",
    "twirling",
    "twister",
    "twisting",
    "tying",
    "umpiring",
    "uncorking bottle",
    "understanding",
    "unicycling",
    "unloading",
    "unscrewing",
    "unsheathing",
    "upside down",
    "using fork",
    "usingtoilet",
    "vacuuming",
    "vaulting",
    "videoing",
    "videotaping",
    "visiting",
    "volleyball",
    "vomiting",
    "voting",
    "vr gaming",
    "wacking face",
    "wading",
    "waiting",
    "wakeboarding",
    "walking",
    "wandering",
    "washing",
    "washing car",
    "watching",
    "waterboarding",
    "waterbucket challenge",
    "watering",
    "waterskiing",
    "waving",
    "waxing",
    "wearing",
    "weaving basket",
    "wedding ceremony",
    "wedgie",
    "weighing",
    "weightlifting",
    "wheelchair",
    "wheeling",
    "whipping",
    "wiffle ball",
    "window shopping",
    "wipeout",
    "woken up",
    "woodworking",
    "working",
    "wrecked",
    "wrestling",
    "writing",
    "yelling",
    "yo-yoing",
    "yoga",
    "zip-lining",
    "ziplining",
    "zoo",
]
